config/routes.rb
Oldmatome::Application.routes.draw do
  root  'products#index'
  get "search" => "products#search"
  get "lcategory" => "products#lcategory"
  get "mcategory" => "products#mcategory"
  get "scategory" => "products#scategory"
  get 'get_amazonpc' => 'products#amazonpc'
  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :product_name, presence: true, uniqueness: true
  serialize :spec, Hash
  def self.search(search)
    if search
      Product.where([ 'product_name LIKE ?', "%#{search}%"])
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :headmetatag_control
  add_breadcrumb 'Home', '/'

  def search
    @products = Product.search(params[:search]).paginate(page: params[:page],:per_page => 40)
    @search_title = params[:search]
    add_breadcrumb '商品検索'
    add_breadcrumb "#{@search_title}の中古商品一覧"
  end

  def index
    @products = Product.paginate(page: params[:page], :per_page => 40)
  end

  def show
    add_breadcrumb @product.l_category, lcategory_path(:lcat => LCategory.find_by_l_category(@product.l_category).id)
    add_breadcrumb @product.m_category, mcategory_path(:mcat => MCategory.find_by_m_category(@product.m_category).id)
    add_breadcrumb @product.s_category, scategory_path(:scat => SCategory.find_by_s_category(@product.s_category).id)
    add_breadcrumb @product.product_name
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def lcategory
    Logger.new("/tmp/log").debug( params)
    @category = [params[:lcat]]
    @products = Product.find_all_by_l_category(LCategory.find_by_id(@category).l_category).paginate(page: params[:page])
    add_breadcrumb LCategory.find_by_id(@category).l_category
  end

  def mcategory
    @category = [params[:mcat]]
    @products = Product.find_all_by_m_category(MCategory.find_by_id(@category).m_category).paginate(page: params[:page])
    add_breadcrumb MCategory.find_by_id(@category).l_category.l_category, lcategory_path(:lcat => MCategory.find_by_id(@category).l_category.id)
    add_breadcrumb MCategory.find_by_id(@category).m_category
  end

  def scategory
    @category = [params[:scat]]
    @products = Product.find_all_by_s_category(SCategory.find_by_id(@category).s_category).paginate(page: params[:page])
    add_breadcrumb SCategory.find_by_id(@category).l_category.l_category, lcategory_path(:lcat => SCategory.find_by_id(@category).l_category.id)
    add_breadcrumb SCategory.find_by_id(@category).m_category.m_category, mcategory_path(:mcat => SCategory.find_by_id(@category).m_category.id)
    add_breadcrumb SCategory.find_by_id(@category).s_category
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def headmetatag_control
    if request.path_info == "/"
      @titletag = "UsedX-中古家電の総合価格比較サイト"
      @meta_keyword ="中古,中古家電,中古パソコン,中古カメラ,中古携帯,中古エアコン,中古洗濯機,中古テレビ"
      @meta_description ="中古家電の総合価格比較サイトUsedX! あらゆる中古家電、PC、スマホの価格を簡単比較。ほしい商品を一番安く買えるサイト！"
      @robots ="index,follow"
      @canonical = "http://rpssales.com/"
    elsif @product
      @titletag = "#{@product.product_name}の中古価格一覧 | UsedX"
      @meta_keyword ="#{@product.product_name}, #{@product.brand},#{@product.series},中古価格,仕様,スペック, オークション,最安値"
      @meta_description ="#{@product.product_name}の中古価格一覧。アマゾン、楽天、ヤフオク、ebayから比較して一番安い価格を確認！"
      @robots ="index,follow"
      @canonical = request.path_info
    elsif params[:search]
      @titletag ="#{params[:search]}の中古商品検索結果 | UsedX"
      @meta_keyword ="#{params[:search]},中古価格,仕様,スペック, オークション,最安値"
      @meta_description ="#{params[:search]}の中古商品一覧。アマゾン、楽天、ヤフオク、ebayから比較して一番安い価格を確認！"
      @robots ="index,follow"
      @canonical = request.path_info
    elsif params[:lcat]
      @category = [params[:lcat]]
      @titletag ="#{LCategory.find_by(id: @category).l_category}の中古商品一覧 | UsedX"
      @meta_keyword ="#{LCategory.find_by(id: @category).l_category},中古価格,仕様,スペック, オークション,最安値"
      @meta_description ="#{LCategory.find_by(id: @category).l_category}の中古商品一覧。アマゾン、楽天、ヤフオク、ebayから比較して一番安い価格を確認！"
      @robots ="index,follow"
      @canonical = request.path_info
    elsif params[:mcat]
      @category = [params[:mcat]]
      @titletag ="#{MCategory.find_by(id: @category).m_category}の中古商品一覧 | UsedX"
      @meta_keyword ="#{MCategory.find_by(id: @category).m_category},中古価格,仕様,スペック, オークション,最安値"
      @meta_description ="#{MCategory.find_by(id: @category).m_category}の中古商品一覧。アマゾン、楽天、ヤフオク、ebayから比較して一番安い価格を確認！"
      @robots ="index,follow"
      @canonical = request.path_info
    elsif params[:scat]
      @category = [params[:scat]]
      @titletag ="#{SCategory.find_by(id: @category).s_category}の中古商品一覧 | UsedX"
      @meta_keyword ="#{SCategory.find_by(id: @category).s_category},中古価格,仕様,スペック, オークション,最安値"
      @meta_description ="#{SCategory.find_by(id: @category).s_category}の中古商品一覧。アマゾン、楽天、ヤフオク、ebayから比較して一番安い価格を確認！"
      @robots ="index,follow"
      @canonical = request.path_info
    else
      @titletag = "UsedX-中古家電の総合価格比較サイト"
      @meta_keyword ="中古,中古家電,中古パソコン,中古カメラ,中古携帯,中古エアコン,中古洗濯機,中古テレビ"
      @meta_description ="中古家電の総合価格比較サイトUsedX! あらゆる中古家電、PC、スマホの価格を簡単比較。ほしい商品を一番安く買えるサイト！"
      @robots ="index,follow"
      @canonical = request.path_info
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:product_name, :model, :brand, :new_price)
  end
end

app/helpers/products_helper.rb
require "open-uri"
require "nokogiri"

module ProductsHelper

  YAHOO_API_ID = "dj0zaiZpPUNIRG1wZE55bEJ1UyZzPWNvbnN1bWVyc2VjcmV0Jng9ZGQ-"

  def get_yahoopc

    enc_word = URI.encode(@product.product_name)
    url1 = "http://auctions.yahooapis.jp/AuctionWebService/V2/search?appid=#{YAHOO_API_ID}&query=#{enc_word}"
    #yahoo shopping用
    # url2 = "http://shopping.yahooapis.jp/ShoppingWebService/V1/itemSearch?appid=#{YAHOO_API_ID}&query=#{enc_word}"
    doc1 = Nokogiri::XML(open(url1))
    # doc2 = Nokogiri::XML(open(url2))
    if @yahoo_price = doc1.xpath('//xmlns:CurrentPrice').first
      @yahoo_price = doc1.xpath('//xmlns:CurrentPrice').first.text
      @yahoo_detail = doc1.xpath('//xmlns:AuctionItemUrl').first.text
      # @yahoos_price = doc2.xpath('//xmlns:Price').first.text
      # @yahoos_detail = doc2.xpath('//xmlns:Url').first.text
    end

  end

  def get_amazonpc
    @keyword = @product.product_name
    Amazon::Ecs.debug = true
    begin
      @res = Amazon::Ecs.item_search(@keyword, 
                                     :item_page => 1, :search_index => 'All', :response_group => 'Medium')
      logger.debug(@res.inspect)
      if @res.items.first
        @amazon_price = @res.items.first.get('OfferSummary/LowestUsedPrice/Amount') 
        @amazon_price2 = @res.items.first.get('OfferSummary/LowestNewPrice/Amount') 
        @amazon_detail = @res.items.first.get('DetailPageURL')
        #    else
        #      @amazon_recommend = @res.items.get('MoreSearchResultsUrl')
      end
    rescue
    end
  end

  def get_rakutenpc
    enc_key = URI.escape(@product.product_name.gsub(/\[|\]/, " "))
    url = "http://search.rakuten.co.jp/search/mall/#{enc_key}/"
    doc = Nokogiri::HTML(open(url), nil, "UTF-8" )
    if @rakuten_detail = doc.xpath('//div[@id="ratArea"]/div/div[@class = "rsrSResultItemInfo"]/p[@class ="price"]/a/@href').first
      @rakuten_price = doc.xpath('//div[@id="ratArea"]/div/div[@class = "rsrSResultItemInfo"]/p[@class ="price"]/a').first.text.gsub(/[^0-9]/,"").to_i
      @rakuten_detail = doc.xpath('//div[@id="ratArea"]/div/div[@class = "rsrSResultItemInfo"]/p[@class ="price"]/a/@href').first.text
    end
  end
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :model_number %><br>
    <%= f.text_field :model_number %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product_list.html.erb
<% if @products.present? %>
<span class="apple_pagination col-sm-10" >
  <%= will_paginate  :class => 'center' %>
</span>
  <div class="col-sm-10">
    <% @products.each do |product| %>
      <div class="col-sm-3 img-rounded">
        <div class="panel panel-default">
          <div class="panel-body">
            <%= link_to product, data: { no_turbolink: true }  do %>
              <%= image_tag product.img_url, {:style => 'border: none;', :class => 'img-rounded'} %>
          </div>
          <div class="panel-footer">
            <ul>
              <li class="panel-price"><%=  number_to_currency([product.new_price.to_i, product.amazon_price.to_i, product.rakuten_price.to_i, product.yahoo_price.to_i, product.ebay_price.to_i].select {|item| item > 0 }.min,:unit => "￥", :precision => 0) %></li>
              <li><%= product.product_name %></li>
            <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %> 
  </div>
<span class="apple_pagination" >
    <%= will_paginate  :class => 'center' %>
</span>
<% end %> 

app/views/products/_product_list_top.html.erb
<% if @products.present? %>
  <span class="apple_pagination" >
    <%= will_paginate  :class => 'center' %>
  </span>
  <div class="col-sm-12">
    <% @products.each do |product| %>
      <div class="col-sm-3 img-rounded">
        <div class="panel panel-default">
          <div class="panel-body">
            <%= link_to product,data: { no_turbolink: true }  do %>
              <%= image_tag product.img_url, {:style => 'border: none;', :class => 'img-rounded'} %>
          </div>
          <div class="panel-footer">
            <ul>
              <li class="panel-price"><%= number_to_currency([product.new_price.to_i, product.amazon_price.to_i, product.rakuten_price.to_i, product.yahoo_price.to_i, product.ebay_price.to_i].select {|item| item > 0 }.min, :unit => "￥", :precision => 0) %></li>
              <li><%= product.product_name %></li>
            <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %> 
  </div>
  <span class="apple_pagination" >
    <%= will_paginate  :class => 'center' %>
  </span>
<% end %> 

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/get_amazonpc.js.erb
$("#amazonpc).html(             
  "<%= @product.get_amazonpc %>"
);

app/views/products/index.html.erb
<div class="left hero-unit">
  <h1>中古PC・家電の最安価格を検索！</h1><br>
  <%= image_tag("search_girl.png", :class => "col-sm-2 img-responsive") %>
  <form class="form-horizontal col-sm-10" role="form" action="/search" method="get">
    <div class="form-group">
      <div class=" col-sm-10 vcenter">
        <input type="search" name="search" class="form-control" placeholder="商品名、型番、メーカーを入力してください" value="<%= params[:search] %>">
      </div>
      <div class="col-sm-2 vcenter">
        <button type="submit" class="btn btn-default btn-warning">検索</button>
      </div>
    </div>
  </form>
  <div class="clearfix col-sm-offset-2 description">
    <h2>新品価格と比較して、お得な中古家電を探そう！</h2>
  </div><hr>
  <h2>カテゴリ</h2>
  <section class = "top-menu">
  <% LCategory.all.each do |lc| %>
    <div class="col-sm-3">
      <h3><%=link_to lc.l_category, lcategory_path(:lcat => lc.id) %></h3>
      <ul>
        <% lc.m_categories.each do |mc| %>
          <li><%=link_to mc.m_category, mcategory_path(:mcat => mc.id) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  </section>
  <%= render 'product_list_top' %>
</div>

app/views/products/lcategory.html.erb
<div id="content">
  <div class="container">
    <div>
      <%= render_breadcrumbs separator: ' > ' %>
    </div>
    <form class="form-horizontal col-sm-10" role="form" action="/search" method="get">
      <div class="form-group">
        <div class=" col-sm-10 vcenter">
          <input type="search" name="search" class="form-control" placeholder="商品名、型番、メーカーを入力してください" value="<%= params[:search] %>">
        </div>
        <div class="col-sm-2 vcenter">
          <button type="submit" class="btn btn-default btn-warning">検索</button>
        </div>
      </div>
    </form>
    <div class="clearfix"></div><hr>

    <div class="col-sm-2 left-menu">
      <h1 class="left"><font size="3%"><%= "#{LCategory.find_by(id: @category).l_category }一覧" %></font></h1>
      <% LCategory.find_by_id(@category).m_categories.each do |mc| %>
        <div class="clearfix">
          <h3><%=link_to mc.m_category, mcategory_path(:mcat => mc.id) %></h3>
          <% mc.s_categories.each do |sc| %>
            <ul>
              <li><%=link_to sc.s_category, scategory_path(:scat => sc.id) %></li>
            </ul> 
          <% end %>
        </div>
      <% end %>
    </div>
    <%= render 'product_list' %>

  </div>
</div>

app/views/products/mcategory.html.erb
<div id="content">
  <div class="container">
    <div>
      <%= render_breadcrumbs separator: ' > ' %>
    </div>
    <form class="form-horizontal col-sm-10" role="form" action="/search" method="get">
      <div class="form-group">
        <div class=" col-sm-10 vcenter">
          <input type="search" name="search" class="form-control" placeholder="商品名、型番、メーカーを入力してください" value="<%= params[:search] %>">
        </div>
        <div class="col-sm-2 vcenter">
          <button type="submit" class="btn btn-default btn-warning">検索</button>
        </div>
      </div>
    </form>
    <div class="clearfix"></div><hr>

    <div class=" col-sm-2 left-menu">
      <h1 class="center"><%= MCategory.find_by(id: @category).m_category  %>一覧</h1><br>
      <h3><%= MCategory.find_by(id: @category).m_category  %></h3>
      <% MCategory.find_by_id(@category).s_categories.each do |sc| %>
        <div class="clearfix">
          <ul><li><%=link_to sc.s_category, scategory_path(:scat => sc.id) %></li></ul>
        </div>
      <% end %>
    </div>

    <%= render 'product_list' %>

  </div>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/scategory.html.erb
<div id="content">
  <div class="container">
    <div>
      <%= render_breadcrumbs separator: ' > ' %>
    </div>
    <form class="form-horizontal col-sm-10" role="form" action="/search" method="get">
      <div class="form-group">
        <div class=" col-sm-10 vcenter">
          <input type="search" name="search" class="form-control" placeholder="商品名、型番、メーカーを入力してください" value="<%= params[:search] %>">
        </div>
        <div class="col-sm-2 vcenter">
          <button type="submit" class="btn btn-default btn-warning">検索</button>
        </div>
      </div>
    </form>
    <div class="clearfix"></div><hr>
    <h1 class="left"><font size="3%"><%= "#{SCategory.find_by(id: @category).s_category }一覧" %></font></h1>
    <%= render 'product_list_top' %>
  </div>
</div>

app/views/products/search.html.erb
<div id="content">
  <div class="container">
    <%= render_breadcrumbs separator: ' > ' %>
  <form class="form-horizontal col-sm-10" role="form" action="/search" method="get">
    <div class="form-group">
      <div class=" col-sm-10 vcenter">
        <input type="search" name="search" class="form-control" placeholder="商品名、型番、メーカーを入力してください" value="<%= params[:search] %>">
      </div>
      <div class="col-sm-2 vcenter">
        <button type="submit" class="btn btn-default btn-warning">検索</button>
      </div>
    </div>
  </form>
  <div class="clearfix"></div><hr>

    <div class="col-sm-2 left-menu">
      <h1 class="left"><font size="3%"><%= "#{params[:search]}一覧" %></font></h1>
      <% LCategory.all.each do |lc| %>
        <div class="clearfix">
          <h3><%=link_to lc.l_category, lcategory_path(:lcat => lc.id) %></h3>
          <ul>
            <% lc.m_categories.each do |mc| %>
              <li><%=link_to mc.m_category, mcategory_path(:mcat => mc.id) %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
      </div>
    <%= render 'product_list' %>

  </div>
</div>

app/views/products/show.html.erb
<div id="content">
  <div class="container">
    <%= render_breadcrumbs separator: ' > ' %>
    <p id="notice"><%= notice %></p>

    <div class="row">
      <div class="col-sm-3">
        <div class="panel panel-default">
          <div class="panel-body">
              <%= image_tag @product.img_url, {:style => 'border: none;', :class => 'img-rounded'} %>
          </div>
        </div>
      </div>
      <div class="col-sm-9 product">
        <h1 class="left"><%= @product.product_name %>の中古価格</h1><hr>
        <div class="col-sm-4 product">
          <ul>
            <li>メーカー：<%= @product.brand %></li>               
            <% if @product.series %>
              <li>シリーズ名：<%= @product.series %> </li>
            <% end %>
            <li class="product_price">新品最安値：<%= number_to_currency(@product.new_price, :unit => "￥", :precision => 0) %></li>
            <li><a href= <%=@product.kakaku_url%>  class ="btn btn-success" target ="_blank" >価格.comで見る <span class="glyphicon glyphicon-hand-right"></span></a></li>
          </ul>
        </div>
        <div class="col-sm-8">
          <table class="table table-striped pricebox">
            <% #get_amazonpc %>
            <% #get_yahoopc %>
            <% #get_rakutenpc %>
            <tbody>
          <tr>
            <th colspan="4" class="left">中古最安価格一覧</th>
          </tr>
              <tr>
                <td>Amazon（アマゾン）</td>
                <td class = "panel-price"><%= @product.amazon_price ? number_to_currency(@product.amazon_price, :unit => "￥", :precision => 0) : "商品がありません"%></td>
                <td><%=@product.amazon_url ? (link_to "商品詳細を見る",  @product.amazon_url,:target=>["_blank"], :class => "btn btn-warning") : "---" %> </td>
                <td><a href= "http://www.amazon.co.jp/s/field-keywords=<%=@product.product_name.gsub(/\[|\]|\?|&|\(|\)\{|\}|\?|\*|\/|\+/, " ")%>/?_encoding=UTF8&camp=247&creative=1211&linkCode=ur2&tag=hiroshixps-22/"  target ="_blank" ><span class="glyphicon glyphicon-th-list"></span><%= @product.amazon_price ?  " 商品一覧をみる": " 類似商品を確認する"%></a></td>
              </tr>
              <tr>
                <td>楽天中古市場</td>
                <td class = "panel-price"><%= @product.rakuten_price ? number_to_currency(@product.rakuten_price, :unit => "￥", :precision => 0) :  "商品がありません"%></td>
                <td><%=@product.rakuten_url ? (link_to "商品詳細を見る ",  @product.rakuten_url,:target=>["_blank"], :class => "btn btn-warning") : "---" %> </td>
                <td><a href= "http://hb.afl.rakuten.co.jp/hgc/0e6d5595.f4187c7a.0e6d5596.9b1eb6e7/?pc=http%3a%2f%2fsearch.rakuten.co.jp%2fsearch%2fmall%2f<%=@product.product_name.gsub(/\[|\]|\?|&|\(|\)\{|\}|\?|\*|\/|\+/, " ")%>%2f%3fscid%3daf_link_urltxt&amp;m=http%3a%2f%2fm.rakuten.co.jp%2f/"  target ="_blank" ><span class="glyphicon glyphicon-th-list"></span><%= @product.rakuten_price ?  " 商品一覧をみる": " 類似商品を確認する"%></a></td>
              </tr>
              <tr>
                <td>ヤフオク</td>
                <td class = "panel-price"><%= @product.yahoo_price ? number_to_currency(@product.yahoo_price, :unit => "￥", :precision => 0) :  "商品がありません"%></td>
                <td><%=@product.yahoo_url ? (link_to "商品詳細を見る ",  @product.yahoo_url,:target=>["_blank"], :class => "btn btn-warning") : "---" %> </td>
                <td><a href= "http://ck.jp.ap.valuecommerce.com/servlet/referral?sid=3159712&pid=882988247&vc_url=http%3A%2F%2Fauctions.search.yahoo.co.jp%2Fsearch%3Fp%3D<%=@product.product_name.gsub(/\[|\]|\?|&|\(|\)\{|\}|\?|\*|\/|\+/, " ")%>"  target ="_blank"><span class="glyphicon glyphicon-th-list"></span><%= @product.yahoo_price ?  " 商品一覧をみる": " 類似商品を確認する"%></a></td>
              </tr>
              <tr>
                <td>eBay(イーベイ)</td>
                <td class = "panel-price"><%= @product.ebay_price ? number_to_currency(@product.ebay_price, :unit => "￥", :precision => 0) :  "商品がありません"%></td>
                <td><%=@product.ebay_url ? (link_to "商品詳細を見る ",  @product.ebay_url,:target=>["_blank"], :class => "btn btn-warning") : "---" %> </td>
                <td><a href= "http://www.ebay.com/sch/i.html?&_nkw=<%=@product.product_name.gsub(/\[|\]|\?|&|\(|\)\{|\}|\?|\*|\/|\+|[^ -~｡-ﾟ]/, " ")%>"  target ="_blank"><span class="glyphicon glyphicon-th-list"></span><%= @product.ebay_price ?  " 商品一覧をみる": " 類似商品を確認する"%></a></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <table class="table-bordered table-striped col-sm-10 spec">
        <tbody>
          <tr>
            <th colspan="4" class="center">商品仕様</th>
          </tr>
          <% @product.spec.each_slice(2) do |s| %>
            <tr>
              <th><%= s[0].to_a.first %></td>
              <td><%= s[0].to_a.second %></td>
              <th><%= s[1].to_a.first %></td>
              <td><%= s[1].to_a.second %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>
  </div>
</div>